update=Mon 07 Nov 2016 05:06:01 PM EET
version=1
last_client=kicad
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=/home/todor/svn-new/KiCAD_Components/OLIMEX_Transistors
LibName2=/home/todor/svn-new/KiCAD_Components/OLIMEX_Switches
LibName3=/home/todor/svn-new/KiCAD_Components/OLIMEX_Regulators
LibName4=/home/todor/svn-new/KiCAD_Components/OLIMEX_RCL
LibName5=/home/todor/svn-new/KiCAD_Components/OLIMEX_Power
LibName6=/home/todor/svn-new/KiCAD_Components/OLIMEX_OTHER
LibName7=/home/todor/svn-new/KiCAD_Components/OLIMEX_Jumpers
LibName8=/home/todor/svn-new/KiCAD_Components/OLIMEX_IC
LibName9=/home/todor/svn-new/KiCAD_Components/OLIMEX_Diodes
LibName10=/home/todor/svn-new/KiCAD_Components/OLIMEX_Devices
LibName11=/home/todor/svn-new/KiCAD_Components/OLIMEX_Connectors
LibName12=/home/todor/svn-new/KiCAD_Components/OLIMEX_Buttons
LibName13=/home/todor/svn-new/KiCAD_Components/OLIMEX_Antennas
[pcbnew]
version=1
PageLayoutDescrFile=
LastNetListRead=
PadDrill=0.762
PadDrillOvalY=0.762
PadSizeH=1.524
PadSizeV=1.524
PcbTextSizeV=1.5
PcbTextSizeH=1.5
PcbTextThickness=0.3
ModuleTextSizeV=1
ModuleTextSizeH=1
ModuleTextSizeThickness=0.15
SolderMaskClearance=0.2
SolderMaskMinWidth=0
DrawSegmentWidth=0.3
BoardOutlineThickness=0.254
ModuleOutlineThickness=0.15
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceAjustPassiveValues=0
LabSize=60
ERC_TestSimilarLabels=1
